FROM mcp_base:latest

# Install llm-agents
RUN echo 20260325
RUN sudo npm install -g @google/gemini-cli
RUN sudo npm install -g @anthropic-ai/claude-code
RUN sudo npm install -g claudeignore
RUN sudo npm install -g @openai/codex
